import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  pojoActorSidebar: [
    {
      type: 'autogenerated',
      dirName: 'pojo-actor',
    },
  ],
  actorIacSidebar: [
    {
      type: 'autogenerated',
      dirName: 'actor-iac',
    },
  ],
};

export default sidebars;
